### ISSUE TITLE
addFile deprecated in underlying archiver library

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [eduardolundgren/node-zip-archiver#5]
The underlying Archiver project has changed 19 days ago and dropped the addFile method, I think it was renamed to append, so node-zip-archiver is now broken.

```
error: TypeError: Object [object Object] has no method 'addFile'
    at ......long path.../node_modules/zip-archiver/lib/index.js:61:30
    at Object.oncomplete (fs.js:107:15)
```

**Comment by itamayo** [comment]
It can be useful determine with which version of 'archiver' works.
