### ISSUE TITLE
archiver.createZip is not a function

### ISSUE THREAD

**Issue by Adobe-Android** [eduardolundgren/node-zip-archiver#6]
I'm having issues using the library and this is the error I get.

```
/home/vm/workspace/compression-research/node_modules/zip-archiver/lib/index.js:19
var zip = archiver.createZip({
                       ^
TypeError: archiver.createZip is not a function
    at new Zip (/home/vm/workspace/compression-research/node_modules/zip-archiver/lib/index.js:19:24)
    at compressFile (/home/vm/workspace/compression-research/compress.js:17:16)
    at /home/vm/workspace/compression-research/compress.js:57:9
    at f (/home/vm/workspace/compression-research/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/home/vm/workspace/compression-research/node_modules/glob/glob.js:151:7)
    at Glob.emit (events.js:159:13)
    at Glob._finish (/home/vm/workspace/compression-research/node_modules/glob/glob.js:197:8)
    at done (/home/vm/workspace/compression-research/node_modules/glob/glob.js:182:14)
    at Glob._processReaddir2 (/home/vm/workspace/compression-research/node_modules/glob/glob.js:434:12)
    at /home/vm/workspace/compression-research/node_modules/glob/glob.js:371:17
```

**Comment by Adobe-Android** [comment]
index.js
It looks like you are using a deprecated method on archiver. Try replacing it with this instead.
lines 19 and 20
```
var zip = archiver('zip', {
        zlib: { level: 9 }
    });
```
I'll create a PR.
